/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Action = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "time": t.opt(t.array("Unit")),
  "seeAlsoAction": t.opt(t.array("string")),
  "fromVariant": t.opt("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Action,
};
export default exportedTypeSuite;
