/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Background = t.iface(["Base", "SRD"], {
  "entries": t.opt(t.array("Entry")),
  "ability": t.opt(t.array("Ability")),
  "feats": t.opt(t.array("any")),
  "skillProficiencies": t.opt(t.array("SkillProficiency")),
  "toolProficiencies": t.opt(t.array("ToolProficiency")),
  "languageProficiencies": t.opt(t.array("LanguageProficiency")),
  "skillToolLanguageProficiencies": t.opt(t.array("SkillToolLanguageProficiency")),
  "startingEquipment": t.opt(t.array("StartingEquipment")),
  "fromFeature": t.opt("any"),
  "additionalSpells": t.opt(t.array("any")),
  "prerequisite": t.opt(t.array("Prerequisite")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Background,
};
export default exportedTypeSuite;
