/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Base = t.iface([], {
  "name": "string",
  "source": "string",
  "page": t.opt("number"),
  "alias": t.opt(t.array("string")),
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "hasFluffImages": t.opt("boolean"),
  "hasFluff": t.opt("boolean"),
  "hasRefs": t.opt("boolean"),
  "hasToken": t.opt("boolean"),
  "referenceSources": t.opt(t.array("Source")),
  "otherSources": t.opt(t.array("Source")),
  "additionalSources": t.opt(t.array("Source")),
  "edition": t.opt("string"),
  "_copy": t.opt("any"),
  "_versions": t.opt(t.array("any")),
});

export const Source = t.union("string", t.iface([], {
  "source": "string",
  "page": t.opt("number"),
}));

export const SRD = t.iface([], {
  "srd": t.opt(t.union("boolean", "string")),
  "srd52": t.opt(t.union("boolean", "string")),
  "basicRules": t.opt("boolean"),
  "basicRules2024": t.opt("boolean"),
});

export const Unit = t.union(t.iface([], {
  "number": "number",
  "unit": "string",
  "note": t.opt("string"),
  "condition": t.opt("string"),
}), t.lit('Varies'), t.lit('Free'));

export const ReprintedAs = t.union("string", t.iface([], {
  "uid": "string",
  "tag": "string",
}));

export const Prerequisite = t.iface([], {
  "ability": t.opt(t.array(t.iface([], {
    "str": t.opt("number"),
    "dex": t.opt("number"),
    "con": t.opt("number"),
    "int": t.opt("number"),
    "wis": t.opt("number"),
    "cha": t.opt("number"),
  }))),
  "background": t.opt(t.array(t.iface([], {
    "name": "string",
    "displayEntry": t.opt("string"),
  }))),
  "campaign": t.opt(t.array("string")),
  "exclusiveFeatCategory": t.opt(t.array("string")),
  "feat": t.opt(t.array("string")),
  "featCategory": t.opt(t.array("string")),
  "feature": t.opt(t.array("string")),
  "level": t.opt(t.union("number", t.iface([], {
    "level": "number",
    "class": t.iface([], {
      "name": "string",
      "visible": t.opt("boolean"),
    }),
  }))),
  "other": t.opt("string"),
  "otherSummary": t.opt(t.iface([], {
    "entry": "string",
    "entrySummary": "string",
  })),
  "proficiency": t.opt(t.array(t.iface([], {
    "weapon": t.opt("string"),
    "armor": t.opt("string"),
    "weaponGroup": t.opt("string"),
  }))),
  "spellcasting": t.opt("boolean"),
  "spellcasting2020": t.opt("boolean"),
  "spellcastingFeature": t.opt("boolean"),
  "race": t.opt(t.array(t.iface([], {
    "name": "string",
    "subrace": t.opt("string"),
    "displayEntry": t.opt("string"),
  }))),
});

export const Rarity = t.union(t.lit('none'), t.lit('unknown'), "string");

export const SpellComponents = t.iface([], {
  "v": t.opt("boolean"),
  "s": t.opt("boolean"),
  "m": t.opt("MaterialComponent"),
  "r": t.opt("boolean"),
});

export const MaterialComponent = t.union("string", t.iface([], {
  "text": "string",
  "cost": t.opt("number"),
  "consume": t.opt(t.union("boolean", t.lit('optional'))),
}));

export const ImageRef = t.iface([], {
  "type": t.lit('image'),
  "href": t.iface([], {
    "type": t.union(t.lit('internal'), t.lit('external')),
    "path": "string",
  }),
  "title": t.opt("string"),
  "credit": t.opt("string"),
  "width": t.opt("number"),
  "height": t.opt("number"),
});

export const SkillProficiency = t.iface([], {
  "acrobatics": t.opt("boolean"),
  "athletics": t.opt("boolean"),
  "arcana": t.opt("boolean"),
  "animal handling": t.opt("boolean"),
  "deception": t.opt("boolean"),
  "history": t.opt("boolean"),
  "insight": t.opt("boolean"),
  "intimidation": t.opt("boolean"),
  "investigation": t.opt("boolean"),
  "medicine": t.opt("boolean"),
  "nature": t.opt("boolean"),
  "perception": t.opt("boolean"),
  "performance": t.opt("boolean"),
  "persuasion": t.opt("boolean"),
  "religion": t.opt("boolean"),
  "sleight of hand": t.opt("boolean"),
  "stealth": t.opt("boolean"),
  "survival": t.opt("boolean"),
  "any": t.opt("number"),
  "anyProficientSkill": t.opt("number"),
  "choose": t.opt("Choose"),
});

export const SavingThrowProficiency = t.iface([], {
  "choose": t.opt("Choose"),
});

export const ToolProficiency = t.iface([], {
  "artisan's tools": t.opt("boolean"),
  "alchemist's supplies": t.opt("boolean"),
  "brewer's supplies": t.opt("boolean"),
  "calligrapher's supplies": t.opt("boolean"),
  "carpenter's tools": t.opt("boolean"),
  "cartographer's tools": t.opt("boolean"),
  "cobbler's tools": t.opt("boolean"),
  "cook's utensils": t.opt("boolean"),
  "glassblower's tools": t.opt("boolean"),
  "jeweler's tools": t.opt("boolean"),
  "leatherworker's tools": t.opt("boolean"),
  "mason's tools": t.opt("boolean"),
  "painter's supplies": t.opt("boolean"),
  "potter's tools": t.opt("boolean"),
  "smith's tools": t.opt("boolean"),
  "tinker's tools": t.opt("boolean"),
  "weaver's tools": t.opt("boolean"),
  "woodcarver's tools": t.opt("boolean"),
  "disguise kit": t.opt("boolean"),
  "forgery kit": t.opt("boolean"),
  "gaming set": t.opt("boolean"),
  "dragonchess set": t.opt("boolean"),
  "dice set": t.opt("boolean"),
  "three-dragon ante set": t.opt("boolean"),
  "playing card set": t.opt("boolean"),
  "herbalism kit": t.opt("boolean"),
  "musical instrument": t.opt("boolean"),
  "bagpipes": t.opt("boolean"),
  "drum": t.opt("boolean"),
  "dulcimer": t.opt("boolean"),
  "flute": t.opt("boolean"),
  "horn": t.opt("boolean"),
  "lute": t.opt("boolean"),
  "lyre": t.opt("boolean"),
  "pan flute": t.opt("boolean"),
  "shawm": t.opt("boolean"),
  "viol": t.opt("boolean"),
  "navigator's tools": t.opt("boolean"),
  "thieves' tools": t.opt("boolean"),
  "poisoner's kit": t.opt("boolean"),
  "vehicles": t.opt("boolean"),
  "vehicles (air)": t.opt("boolean"),
  "vehicles (land)": t.opt("boolean"),
  "vehicles (water)": t.opt("boolean"),
  "vehicles (space)": t.opt("boolean"),
  "any": t.opt("number"),
  "anyArtisansTool": t.opt("number"),
  "anyGamingSet": t.opt("number"),
  "anyMusicalInstrument": t.opt("number"),
  "choose": t.opt("Choose"),
});

export const LanguageProficiency = t.iface([], {
  "abyssal": t.opt("boolean"),
  "aquan": t.opt("boolean"),
  "auran": t.opt("boolean"),
  "celestial": t.opt("boolean"),
  "common": t.opt("boolean"),
  "common sign language": t.opt("boolean"),
  "deep speech": t.opt("boolean"),
  "draconic": t.opt("boolean"),
  "druidic": t.opt("boolean"),
  "dwarvish": t.opt("boolean"),
  "elvish": t.opt("boolean"),
  "giant": t.opt("boolean"),
  "gith": t.opt("boolean"),
  "gnomish": t.opt("boolean"),
  "goblin": t.opt("boolean"),
  "halfling": t.opt("boolean"),
  "ignan": t.opt("boolean"),
  "infernal": t.opt("boolean"),
  "orc": t.opt("boolean"),
  "other": t.opt("boolean"),
  "primordial": t.opt("boolean"),
  "sylvan": t.opt("boolean"),
  "terran": t.opt("boolean"),
  "thieves' cant": t.opt("boolean"),
  "undercommon": t.opt("boolean"),
  "any": t.opt("number"),
  "anyStandard": t.opt("number"),
  "choose": t.opt("Choose"),
});

export const SkillToolLanguageProficiency = t.iface([], {
  "choose": t.opt(t.array("Choose")),
  "anyLanguage": t.opt("number"),
  "anyTool": t.opt("number"),
});

export const WeaponProficiency = t.iface([], {
  "firearms": t.opt("boolean"),
  "simple": t.opt("boolean"),
  "martial": t.opt("boolean"),
  "improvised": t.opt("boolean"),
  "choose": t.opt("Choose"),
});

export const ArmorProficiency = t.iface([], {
  "light": t.opt("boolean"),
  "medium": t.opt("boolean"),
  "heavy": t.opt("boolean"),
  "shield": t.opt("boolean"),
});

export const Ability = t.iface([], {
  "str": t.opt("number"),
  "dex": t.opt("number"),
  "con": t.opt("number"),
  "int": t.opt("number"),
  "wis": t.opt("number"),
  "cha": t.opt("number"),
  "choose": t.opt(t.union("Choose", t.array("Choose"))),
  "hidden": t.opt("boolean"),
  "max": t.opt("number"),
});

export const Resist = t.union("string", t.iface([], {
  "choose": t.opt("Choose"),
}));

export const Choose = t.iface([], {
  "from": t.opt(t.array("string")),
  "fromFilter": t.opt("string"),
  "count": t.opt("number"),
  "amount": t.opt("number"),
  "max": t.opt("number"),
  "entry": t.opt("string"),
  "weighted": t.opt(t.iface([], {
    "from": t.array("string"),
    "weights": t.array("number"),
  })),
});

export const Sense = t.iface([], {
  "blindsight": t.opt("number"),
  "truesight": t.opt("number"),
  "darkvision": t.opt("number"),
});

export const AdditionalSpell = t.name("any");

export const FeatureProgression = t.iface([], {
  "name": "string",
  "featureType": t.array("string"),
  "progression": "any",
});

export const Light = t.iface([], {
  "bright": t.opt("number"),
  "dim": t.opt("number"),
  "shape": t.opt("string"),
});

export const SetAbility = t.iface([], {
  "static": t.iface([], {
    "str": t.opt("number"),
    "dex": t.opt("number"),
    "con": t.opt("number"),
    "int": t.opt("number"),
    "wis": t.opt("number"),
    "cha": t.opt("number"),
  }),
});

export const ReqAttuneTag = t.iface([], {
  "alignment": t.opt(t.array("string")),
  "background": t.opt("string"),
  "class": t.opt("string"),
  "creatureType": t.opt("string"),
  "languageProficiency": t.opt("string"),
  "psionics": t.opt("boolean"),
  "race": t.opt("string"),
  "size": t.opt("string"),
  "skillProficiency": t.opt("string"),
  "spellcasting": t.opt("boolean"),
  "str": t.opt("number"),
  "dex": t.opt("number"),
  "con": t.opt("number"),
  "int": t.opt("number"),
  "wis": t.opt("number"),
  "cha": t.opt("number"),
});

export const UIDString = t.union("string", t.iface([], {
  "uid": "string",
  "note": "string",
}));

export const Duration = t.iface([], {
  "type": t.union(t.lit('instant'), t.lit('timed'), t.lit('permanent'), t.lit('special')),
  "duration": t.opt(t.iface([], {
    "type": t.union(t.lit('round'), t.lit('hour'), t.lit('minute'), t.lit('day')),
    "amount": "number",
    "upTo": t.opt("boolean"),
  })),
  "condition": t.opt("string"),
  "concentration": t.opt("boolean"),
  "ends": t.opt(t.array("string")),
});

export const RangeType = t.union(t.lit('special'), t.lit('point'), t.lit('emanation'), t.lit('line'), t.lit('cone'), t.lit('radius'), t.lit('sphere'), t.lit('cylinder'), t.lit('cube'), t.lit('hemisphere'));

export const Range = t.iface([], {
  "type": "RangeType",
  "distance": t.opt(t.iface([], {
    "type": t.union(t.lit('feet'), t.lit('self'), t.lit('touch'), t.lit('miles'), t.lit('sight'), t.lit('unlimited')),
    "amount": t.opt("number"),
  })),
});

export const Scaling = t.iface([], {
  "1": t.opt("string"),
  "2": t.opt("string"),
  "3": t.opt("string"),
  "4": t.opt("string"),
  "5": t.opt("string"),
  "6": t.opt("string"),
  "7": t.opt("string"),
  "8": t.opt("string"),
  "9": t.opt("string"),
  "10": t.opt("string"),
  "11": t.opt("string"),
  "12": t.opt("string"),
  "13": t.opt("string"),
  "14": t.opt("string"),
  "15": t.opt("string"),
  "16": t.opt("string"),
  "17": t.opt("string"),
  "18": t.opt("string"),
  "19": t.opt("string"),
  "20": t.opt("string"),
});

export const ScalingLevelDice = t.iface([], {
  "label": t.opt("string"),
  "scaling": "Scaling",
});

export const StartingEquipmentEntry = t.union("string", t.iface([], {
  "value": "number",
}), t.iface([], {
  "item": "string",
  "displayName": t.opt("string"),
  "containsValue": t.opt("number"),
  "quantity": t.opt("number"),
}), t.iface([], {
  "special": "string",
  "quantity": t.opt("number"),
  "worthValue": t.opt("number"),
  "containsValue": t.opt("number"),
}), t.iface([], {
  "equipmentType": "string",
  "displayName": t.opt("string"),
}));

export const StartingEquipment = t.iface([], {
  "_": t.opt(t.array("StartingEquipmentEntry")),
  "a": t.opt(t.array("StartingEquipmentEntry")),
  "b": t.opt(t.array("StartingEquipmentEntry")),
  "c": t.opt(t.array("StartingEquipmentEntry")),
  "d": t.opt(t.array("StartingEquipmentEntry")),
  "A": t.opt(t.array("StartingEquipmentEntry")),
  "B": t.opt(t.array("StartingEquipmentEntry")),
  "C": t.opt(t.array("StartingEquipmentEntry")),
  "D": t.opt(t.array("StartingEquipmentEntry")),
});

export const DangerRating = t.iface([], {
  "tier": "number",
  "threat": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Base,
  Source,
  SRD,
  Unit,
  ReprintedAs,
  Prerequisite,
  Rarity,
  SpellComponents,
  MaterialComponent,
  ImageRef,
  SkillProficiency,
  SavingThrowProficiency,
  ToolProficiency,
  LanguageProficiency,
  SkillToolLanguageProficiency,
  WeaponProficiency,
  ArmorProficiency,
  Ability,
  Resist,
  Choose,
  Sense,
  AdditionalSpell,
  FeatureProgression,
  Light,
  SetAbility,
  ReqAttuneTag,
  UIDString,
  Duration,
  RangeType,
  Range,
  Scaling,
  ScalingLevelDice,
  StartingEquipmentEntry,
  StartingEquipment,
  DangerRating,
};
export default exportedTypeSuite;
