/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Boon = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "type": "string",
  "ability": t.opt("SingleEntry"),
  "signatureSpells": t.opt("SingleEntry"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Boon,
};
export default exportedTypeSuite;
