/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Base = t.iface([], {
  "name": "string",
  "source": "string",
  "page": t.opt("number"),
  "alias": t.opt(t.array("string")),
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "hasFluffImages": t.opt("boolean"),
  "hasFluff": t.opt("boolean"),
  "hasRefs": t.opt("boolean"),
  "referenceSources": t.opt(t.array("Source")),
  "otherSources": t.opt(t.array("Source")),
  "additionalSources": t.opt(t.array("Source")),
  "_copy": t.opt("any"),
});

export const Source = t.union("string", t.iface([], {
  "source": "string",
  "page": t.opt("number"),
}));

export const SRD = t.iface([], {
  "srd": t.opt(t.union("boolean", "string")),
  "srd52": t.opt(t.union("boolean", "string")),
  "basicRules": t.opt("boolean"),
  "basicRules2024": t.opt("boolean"),
});

export const Unit = t.union(t.iface([], {
  "number": "number",
  "unit": "string",
  "note": t.opt("string"),
  "condition": t.opt("string"),
}), t.lit('Varies'), t.lit('Free'));

export const ReprintedAs = t.union("string", t.iface([], {
  "uid": "string",
  "tag": "string",
}));

export const Entry = t.union("string", "EntryEntries", "EntryItem", "EntrySection", "EntryInset", "EntryTable", "EntryList", "EntryQuote");

export const EntryEntries = t.iface([], {
  "type": t.lit('entries'),
  "name": t.opt("string"),
  "page": t.opt("number"),
  "entries": t.array("Entry"),
});

export const EntryItem = t.iface([], {
  "type": t.lit('item'),
  "name": t.opt("string"),
  "entries": t.opt(t.array("Entry")),
  "entry": t.opt("Entry"),
});

export const EntrySection = t.iface([], {
  "type": t.lit('section'),
  "name": t.opt("string"),
  "entries": t.array("Entry"),
});

export const EntryInset = t.iface([], {
  "type": t.lit('inset'),
  "source": t.opt("string"),
  "page": t.opt("number"),
  "name": "string",
  "entries": t.array("Entry"),
});

export const EntryTableGroup = t.iface([], {
  "type": t.lit('tableGroup'),
  "name": "string",
  "caption": t.opt("string"),
  "tables": t.array("EntryTable"),
});

export const EntryTable = t.iface([], {
  "type": t.lit('table'),
  "caption": t.opt("string"),
  "colLabels": t.opt(t.array("string")),
  "colLabelRows": t.opt(t.array("ColLabelRow")),
  "colStyles": t.array("string"),
  "rows": t.array(t.array(t.union("Entry", "Cell"))),
  "footnote": t.opt("string"),
  "footnotes": t.opt(t.array("string")),
  "data": t.opt("any"),
});

export const ColLabelRow = t.array(t.union("string", t.iface([], {
  "entry": "string",
  "width": "number",
})));

export const Cell = t.iface([], {
  "type": t.lit('cell'),
  "roll": t.union(t.iface([], {
    "exact": "number",
  }), t.iface([], {
    "min": "number",
    "max": "number",
    "pad": t.opt("boolean"),
  })),
  "entry": t.opt("Entry"),
});

export const EntryList = t.iface([], {
  "type": t.lit('list'),
  "style": t.opt("string"),
  "columns": t.opt("number"),
  "items": t.array("Entry"),
});

export const EntryQuote = t.iface([], {
  "type": t.lit('quote'),
  "entries": t.array("Entry"),
  "by": t.opt("string"),
});

export const SingleEntry = t.iface([], {
  "entry": "string",
});

export const Prerequisite = t.iface([], {
  "ability": t.opt(t.array(t.iface([], {
    "str": t.opt("number"),
    "dex": t.opt("number"),
    "con": t.opt("number"),
    "int": t.opt("number"),
    "wis": t.opt("number"),
    "cha": t.opt("number"),
  }))),
  "background": t.opt(t.array(t.iface([], {
    "name": "string",
    "displayEntry": t.opt("string"),
  }))),
  "campaign": t.opt(t.array("string")),
  "exclusiveFeatCategory": t.opt(t.array("string")),
  "feat": t.opt(t.array("string")),
  "featCategory": t.opt(t.array("string")),
  "feature": t.opt(t.array("string")),
  "level": t.opt(t.union("number", t.iface([], {
    "level": "number",
    "class": t.iface([], {
      "name": "string",
      "visible": t.opt("boolean"),
    }),
  }))),
  "other": t.opt("string"),
  "otherSummary": t.opt(t.iface([], {
    "entry": "string",
    "entrySummary": "string",
  })),
  "proficiency": t.opt(t.array(t.iface([], {
    "weapon": t.opt("string"),
    "armor": t.opt("string"),
    "weaponGroup": t.opt("string"),
  }))),
  "spellcasting": t.opt("boolean"),
  "spellcasting2020": t.opt("boolean"),
  "spellcastingFeature": t.opt("boolean"),
  "race": t.opt(t.array(t.iface([], {
    "name": "string",
    "subrace": t.opt("string"),
    "displayEntry": t.opt("string"),
  }))),
});

export const Rarity = t.union(t.lit('none'), t.lit('unknown'), "string");

export const SpellComponents = t.iface([], {
  "v": t.opt("boolean"),
  "s": t.opt("boolean"),
  "m": t.opt("MaterialComponent"),
  "r": t.opt("boolean"),
});

export const MaterialComponent = t.union("string", t.iface([], {
  "text": "string",
  "cost": t.opt("number"),
  "consume": t.opt(t.union("boolean", t.lit('optional'))),
}));

export const ImageRef = t.iface([], {
  "type": "string",
  "href": t.iface([], {
    "type": "string",
    "path": "string",
  }),
  "credit": "string",
  "width": "number",
  "height": "number",
});

export const SkillProficiency = t.iface([], {
  "acrobatics": t.opt("boolean"),
  "athletics": t.opt("boolean"),
  "arcana": t.opt("boolean"),
  "animal handling": t.opt("boolean"),
  "deception": t.opt("boolean"),
  "history": t.opt("boolean"),
  "insight": t.opt("boolean"),
  "intimidation": t.opt("boolean"),
  "investigation": t.opt("boolean"),
  "medicine": t.opt("boolean"),
  "nature": t.opt("boolean"),
  "perception": t.opt("boolean"),
  "performance": t.opt("boolean"),
  "persuasion": t.opt("boolean"),
  "religion": t.opt("boolean"),
  "sleight of hand": t.opt("boolean"),
  "stealth": t.opt("boolean"),
  "survival": t.opt("boolean"),
  "any": t.opt("number"),
  "anyProficientSkill": t.opt("number"),
  "choose": t.opt("Choose"),
});

export const SavingThrowProficiency = t.iface([], {
  "choose": t.opt("Choose"),
});

export const ToolProficiency = t.iface([], {
  "cook's utensils": t.opt("boolean"),
  "poisoner's kit": t.opt("boolean"),
  "any": t.opt("number"),
  "anyArtisansTool": t.opt("number"),
  "anyMusicalInstrument": t.opt("number"),
  "choose": t.opt("Choose"),
});

export const LanguageProficiency = t.iface([], {
  "draconic": t.opt("boolean"),
  "sylvan": t.opt("boolean"),
  "thieves' cant": t.opt("boolean"),
  "any": t.opt("number"),
});

export const SkillToolLanguageProficiency = t.iface([], {
  "choose": t.opt(t.array("Choose")),
});

export const WeaponProficiency = t.iface([], {
  "firearms": t.opt("boolean"),
  "simple": t.opt("boolean"),
  "martial": t.opt("boolean"),
  "improvised": t.opt("boolean"),
  "choose": t.opt("Choose"),
});

export const ArmorProficiency = t.iface([], {
  "light": t.opt("boolean"),
  "medium": t.opt("boolean"),
  "heavy": t.opt("boolean"),
  "shield": t.opt("boolean"),
});

export const Ability = t.iface([], {
  "str": t.opt("number"),
  "dex": t.opt("number"),
  "con": t.opt("number"),
  "int": t.opt("number"),
  "wis": t.opt("number"),
  "cha": t.opt("number"),
  "choose": t.opt(t.union("Choose", t.array("Choose"))),
  "hidden": t.opt("boolean"),
  "max": t.opt("number"),
});

export const Resist = t.union("string", t.iface([], {
  "choose": t.opt("Choose"),
}));

export const Choose = t.iface([], {
  "from": t.opt(t.array("string")),
  "fromFilter": t.opt("string"),
  "count": t.opt("number"),
  "amount": t.opt("number"),
  "max": t.opt("number"),
  "entry": t.opt("string"),
});

export const Sense = t.iface([], {
  "blindsight": t.opt("number"),
  "truesight": t.opt("number"),
  "darkvision": t.opt("number"),
});

export const AdditionalSpell = t.name("any");

export const FeatureProgression = t.iface([], {
  "name": "string",
  "featureType": t.array("string"),
  "progression": "any",
});

export const Light = t.iface([], {
  "bright": t.opt("number"),
  "dim": t.opt("number"),
  "shape": t.opt("string"),
});

export const SetAbility = t.iface([], {
  "static": t.iface([], {
    "str": t.opt("number"),
    "dex": t.opt("number"),
    "con": t.opt("number"),
    "int": t.opt("number"),
    "wis": t.opt("number"),
    "cha": t.opt("number"),
  }),
});

export const ReqAttuneTag = t.iface([], {
  "alignment": t.opt(t.array("string")),
  "background": t.opt("string"),
  "class": t.opt("string"),
  "creatureType": t.opt("string"),
  "languageProficiency": t.opt("string"),
  "psionics": t.opt("boolean"),
  "race": t.opt("string"),
  "size": t.opt("string"),
  "skillProficiency": t.opt("string"),
  "spellcasting": t.opt("boolean"),
  "str": t.opt("number"),
  "dex": t.opt("number"),
  "con": t.opt("number"),
  "int": t.opt("number"),
  "wis": t.opt("number"),
  "cha": t.opt("number"),
});

export const Mastery = t.union("string", t.iface([], {
  "uid": "string",
  "note": "string",
}));

export const Duration = t.iface([], {
  "type": t.union(t.lit('instant'), t.lit('timed'), t.lit('permanent'), t.lit('special')),
  "duration": t.opt(t.iface([], {
    "type": t.union(t.lit('round'), t.lit('hour'), t.lit('minute'), t.lit('day')),
    "amount": "number",
    "upTo": t.opt("boolean"),
  })),
  "concentration": t.opt("boolean"),
  "ends": t.opt(t.array("string")),
});

export const RangeType = t.union(t.lit('special'), t.lit('point'), t.lit('emanation'), t.lit('line'), t.lit('cone'), t.lit('radius'), t.lit('sphere'), t.lit('cylinder'), t.lit('cube'), t.lit('hemisphere'));

export const Range = t.iface([], {
  "type": "RangeType",
  "distance": t.opt(t.iface([], {
    "type": t.union(t.lit('feet'), t.lit('self'), t.lit('touch'), t.lit('miles'), t.lit('sight'), t.lit('unlimited')),
    "amount": t.opt("number"),
  })),
});

export const Scaling = t.iface([], {
  "1": t.opt("string"),
  "2": t.opt("string"),
  "3": t.opt("string"),
  "4": t.opt("string"),
  "5": t.opt("string"),
  "6": t.opt("string"),
  "7": t.opt("string"),
  "8": t.opt("string"),
  "9": t.opt("string"),
  "10": t.opt("string"),
  "11": t.opt("string"),
  "12": t.opt("string"),
  "13": t.opt("string"),
  "14": t.opt("string"),
  "15": t.opt("string"),
  "16": t.opt("string"),
  "17": t.opt("string"),
  "18": t.opt("string"),
  "19": t.opt("string"),
  "20": t.opt("string"),
});

export const ScalingLevelDice = t.iface([], {
  "label": t.opt("string"),
  "scaling": "Scaling",
});

const exportedTypeSuite: t.ITypeSuite = {
  Base,
  Source,
  SRD,
  Unit,
  ReprintedAs,
  Entry,
  EntryEntries,
  EntryItem,
  EntrySection,
  EntryInset,
  EntryTableGroup,
  EntryTable,
  ColLabelRow,
  Cell,
  EntryList,
  EntryQuote,
  SingleEntry,
  Prerequisite,
  Rarity,
  SpellComponents,
  MaterialComponent,
  ImageRef,
  SkillProficiency,
  SavingThrowProficiency,
  ToolProficiency,
  LanguageProficiency,
  SkillToolLanguageProficiency,
  WeaponProficiency,
  ArmorProficiency,
  Ability,
  Resist,
  Choose,
  Sense,
  AdditionalSpell,
  FeatureProgression,
  Light,
  SetAbility,
  ReqAttuneTag,
  Mastery,
  Duration,
  RangeType,
  Range,
  Scaling,
  ScalingLevelDice,
};
export default exportedTypeSuite;
