/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Unit = t.union(t.iface([], {
  "number": "number",
  "unit": "string",
}), t.lit('Varies'), t.lit('Free'));

export const Entry = t.union("string", "EntryEntries");

export const EntryEntries = t.iface([], {
  "type": t.lit('entries'),
  "name": "string",
  "entries": t.array("Entry"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Unit,
  Entry,
  EntryEntries,
};
export default exportedTypeSuite;
