/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Deity = t.iface(["Base", "SRD"], {
  "entries": t.opt(t.array("Entry")),
  "pantheon": "string",
  "reprintAlias": t.opt("string"),
  "alignment": t.opt(t.array("string")),
  "category": t.opt("string"),
  "title": t.opt("string"),
  "worshipers": t.opt("string"),
  "plane": t.opt("string"),
  "domains": t.opt(t.array("string")),
  "province": t.opt("string"),
  "symbol": t.opt("string"),
  "symbolImg": t.opt("EntryImage"),
  "altNames": t.opt(t.array("string")),
  "piety": t.opt("boolean"),
  "customExtensionOf": t.opt("string"),
  "favoredWeapons": t.opt("string"),
  "dogma": t.opt("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Deity,
};
export default exportedTypeSuite;
