/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Entry = t.union("string", "EntryEntries", "EntryItem", "EntrySection", "EntryInset", "EntryTable", "EntryList", "EntryQuote", "EntryImage");

export const EntryEntries = t.iface([], {
  "type": t.lit('entries'),
  "id": t.opt("string"),
  "name": t.opt("string"),
  "page": t.opt("number"),
  "entries": t.array("Entry"),
  "data": t.opt("any"),
});

export const EntryItem = t.iface([], {
  "type": t.union(t.lit('item'), t.lit('itemSub')),
  "name": t.opt("string"),
  "entries": t.opt(t.array("Entry")),
  "entry": t.opt("Entry"),
});

export const EntrySection = t.iface([], {
  "type": t.lit('section'),
  "id": t.opt("string"),
  "name": t.opt("string"),
  "entries": t.array("Entry"),
});

export const EntryInset = t.iface([], {
  "type": t.union(t.lit('inset'), t.lit('insetReadaloud')),
  "id": t.opt("string"),
  "source": t.opt("string"),
  "page": t.opt("number"),
  "name": t.opt("string"),
  "entries": t.array("Entry"),
});

export const EntryTableGroup = t.iface([], {
  "type": t.lit('tableGroup'),
  "name": "string",
  "caption": t.opt("string"),
  "tables": t.array("EntryTable"),
});

export const EntryTable = t.iface([], {
  "type": t.lit('table'),
  "name": t.opt("string"),
  "caption": t.opt("string"),
  "colLabels": t.opt(t.array("string")),
  "colLabelRows": t.opt(t.array("ColLabelRow")),
  "colStyles": t.array("string"),
  "rows": t.array(t.array(t.union("Entry", "Cell", "number"))),
  "footnote": t.opt("string"),
  "footnotes": t.opt(t.array("string")),
  "data": t.opt("any"),
});

export const ColLabelRow = t.array(t.union("string", t.iface([], {
  "entry": "string",
  "width": "number",
})));

export const Cell = t.iface([], {
  "type": t.lit('cell'),
  "roll": t.union(t.iface([], {
    "exact": "number",
  }), t.iface([], {
    "min": "number",
    "max": "number",
    "pad": t.opt("boolean"),
  })),
  "entry": t.opt("Entry"),
});

export const EntryList = t.iface([], {
  "type": t.lit('list'),
  "name": t.opt("string"),
  "style": t.opt("string"),
  "columns": t.opt("number"),
  "items": t.array("Entry"),
});

export const EntryQuote = t.iface([], {
  "type": t.lit('quote'),
  "entries": t.array("Entry"),
  "by": t.opt("string"),
  "skipMarks": t.opt("boolean"),
});

export const EntryImage = t.iface([], {
  "type": t.lit('image'),
  "href": t.union(t.iface([], {
    "type": t.lit('internal'),
    "path": "string",
  }), t.iface([], {
    "type": t.lit('external'),
    "url": "string",
  })),
  "title": t.opt("string"),
  "credit": t.opt("string"),
  "width": t.opt("number"),
  "height": t.opt("number"),
  "altText": t.opt("string"),
  "style": t.opt("string"),
});

export const SingleEntry = t.iface([], {
  "entry": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Entry,
  EntryEntries,
  EntryItem,
  EntrySection,
  EntryInset,
  EntryTableGroup,
  EntryTable,
  ColLabelRow,
  Cell,
  EntryList,
  EntryQuote,
  EntryImage,
  SingleEntry,
};
export default exportedTypeSuite;
