/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Feat = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "category": t.opt("string"),
  "prerequisite": t.opt(t.array("Prerequisite")),
  "skillProficiencies": t.opt(t.array("SkillProficiency")),
  "toolProficiencies": t.opt(t.array("ToolProficiency")),
  "languageProficiencies": t.opt(t.array("LanguageProficiency")),
  "weaponProficiencies": t.opt(t.array("WeaponProficiency")),
  "armorProficiencies": t.opt(t.array("ArmorProficiency")),
  "savingThrowProficiencies": t.opt(t.array("SavingThrowProficiency")),
  "skillToolLanguageProficiencies": t.opt(t.array("SkillToolLanguageProficiency")),
  "expertise": t.opt(t.array("SkillProficiency")),
  "senses": t.opt(t.array("Sense")),
  "bonusSenses": t.opt(t.array("Sense")),
  "additionalSpells": t.opt(t.array("AdditionalSpell")),
  "ability": t.opt(t.array("Ability")),
  "repeatable": t.opt("boolean"),
  "repeatableHidden": t.opt("boolean"),
  "traitTags": t.opt(t.array("string")),
  "immune": t.opt(t.array("Resist")),
  "resist": t.opt(t.array("Resist")),
  "conditionImmune": t.opt(t.array("string")),
  "optionalfeatureProgression": t.opt(t.array("FeatureProgression")),
  "_versions": t.opt(t.array("any")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Feat,
};
export default exportedTypeSuite;
