/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Fluff = t.iface(["Base"], {
  "entries": t.opt(t.array("Entry")),
  "images": t.opt(t.array("EntryImage")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Fluff,
};
export default exportedTypeSuite;
