/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Hazard = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "rating": t.opt(t.array("DangerRating")),
  "trapHazType": t.opt("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Hazard,
};
export default exportedTypeSuite;
