/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Language = t.iface(["Base", "SRD"], {
  "entries": t.opt(t.array("Entry")),
  "type": t.opt("string"),
  "script": t.opt("string"),
  "origin": t.opt("string"),
  "typicalSpeakers": t.opt(t.array("string")),
  "fonts": t.opt(t.array("string")),
  "dialects": t.opt(t.array("string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Language,
};
export default exportedTypeSuite;
