/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Skill = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "ability": t.union(t.lit('str'), t.lit('dex'), t.lit('con'), t.lit('int'), t.lit('wis'), t.lit('cha')),
});

const exportedTypeSuite: t.ITypeSuite = {
  Skill,
};
export default exportedTypeSuite;
