/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const SpellSource = t.iface([], {
  "spellName": "string",
  "spellSource": "string",
  "casterName": "string",
  "casterSource": "string",
});

export const Spell = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "entriesHigherLevel": t.opt(t.array("Entry")),
  "level": "number",
  "school": "string",
  "components": "SpellComponents",
  "time": t.opt(t.array("Unit")),
  "duration": t.opt(t.array("Duration")),
  "range": t.opt("Range"),
  "damageInflict": t.opt(t.array("string")),
  "damageImmune": t.opt(t.array("Resist")),
  "damageResist": t.opt(t.array("Resist")),
  "damageVulnerable": t.opt(t.array("Resist")),
  "conditionInflict": t.opt(t.array("string")),
  "conditionImmune": t.opt(t.array("string")),
  "savingThrow": t.opt(t.array("string")),
  "affectsCreatureType": t.opt(t.array("string")),
  "areaTags": t.opt(t.array("string")),
  "scalingLevelDice": t.opt(t.union("ScalingLevelDice", t.array("ScalingLevelDice"))),
  "miscTags": t.opt(t.array("string")),
  "meta": t.opt(t.iface([], {
    "ritual": "boolean",
  })),
  "spellAttack": t.opt(t.array("string")),
  "abilityCheck": t.opt(t.array("string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  SpellSource,
  Spell,
};
export default exportedTypeSuite;
