/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Table = t.iface(["Base", "SRD"], {
  "caption": t.opt("string"),
  "colLabels": t.opt(t.array("string")),
  "colStyles": t.array("string"),
  "rows": t.array(t.array(t.union("Entry", "Cell"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  Table,
};
export default exportedTypeSuite;
