/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Trap = t.iface(["Base", "SRD"], {
  "entries": t.array("Entry"),
  "rating": t.opt(t.array("DangerRating")),
  "trapHazType": t.opt("string"),
  "trigger": t.opt(t.array("string")),
  "countermeasures": t.opt(t.array("Entry")),
  "effect": t.opt(t.array("string")),
  "duration": t.opt(t.array("Duration")),
  "hauntBonus": t.opt("string"),
  "initiative": t.opt("number"),
  "initiativeNote": t.opt("string"),
  "eActive": t.opt(t.array("Entry")),
  "eDynamic": t.opt(t.array("Entry")),
  "eConstant": t.opt(t.array("Entry")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Trap,
};
export default exportedTypeSuite;
