/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Action = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "entries": t.array("Entry"),
  "time": t.opt(t.array("Unit")),
});

export const Boon = t.iface([], {
  "name": "string",
  "source": "string",
  "type": "string",
  "ability": t.opt("SingleEntry"),
  "signatureSpells": t.opt("SingleEntry"),
  "entries": t.array("Entry"),
});

export const Deity = t.iface([], {
  "name": "string",
  "source": "string",
  "pantheon": "string",
  "alignment": t.opt(t.array("string")),
  "category": t.opt("string"),
  "title": t.opt("string"),
  "worshipers": t.opt("string"),
  "plane": t.opt("string"),
  "domains": t.opt(t.array("string")),
  "province": t.opt("string"),
  "symbol": t.opt("string"),
  "symbolImg": t.opt("ImageRef"),
  "entries": t.opt(t.array("string")),
});

export const Feat = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "category": t.opt("string"),
  "entries": t.array("Entry"),
  "prerequisite": t.opt(t.array("Prerequisite")),
  "hasFluffImages": t.opt("boolean"),
});

export const ItemMastery = t.iface([], {
  "name": "string",
  "source": "string",
  "entries": t.array("Entry"),
});

export const ItemProperty = t.iface([], {
  "name": t.opt("string"),
  "source": "string",
  "abbreviation": "string",
  "template": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "entries": t.opt(t.array("Entry")),
});

export const Item = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "type": t.opt("string"),
  "rarity": t.opt("Rarity"),
  "wondrous": t.opt("boolean"),
});

export const Spell = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "entries": t.array("Entry"),
  "entriesHigherLevel": t.opt(t.array("Entry")),
  "level": "number",
  "school": "string",
  "components": "SpellComponents",
});

export const Table = t.iface([], {
  "name": "string",
  "source": "string",
  "caption": t.opt("string"),
  "colLabels": t.opt(t.array("string")),
  "colStyles": t.array("string"),
  "rows": t.array(t.array(t.union("Entry", "Cell"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  Action,
  Boon,
  Deity,
  Feat,
  ItemMastery,
  ItemProperty,
  Item,
  Spell,
  Table,
};
export default exportedTypeSuite;
