/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Action = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "entries": t.array("Entry"),
  "time": t.opt(t.array("Unit")),
});

export const Feat = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "category": t.opt("string"),
  "entries": t.array("Entry"),
  "prerequisite": t.opt(t.array("Prerequisite")),
  "hasFluffImages": t.opt("boolean"),
});

export const ItemMastery = t.iface([], {
  "name": "string",
  "source": "string",
  "entries": t.array("Entry"),
});

export const ItemProperty = t.iface([], {
  "name": t.opt("string"),
  "source": "string",
  "abbreviation": "string",
  "template": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "entries": t.opt(t.array("Entry")),
});

export const Item = t.iface([], {
  "name": "string",
  "source": "string",
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "type": t.opt("string"),
  "rarity": t.opt("Rarity"),
  "wondrous": t.opt("boolean"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Action,
  Feat,
  ItemMastery,
  ItemProperty,
  Item,
};
export default exportedTypeSuite;
