/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Action = t.iface([], {
  "name": "string",
  "source": "string",
  "page": "number",
  "entries": t.array("Entry"),
  "time": t.opt(t.array("Unit")),
  "reprintedAs": t.opt(t.array("ReprintedAs")),
});

export const Feat = t.iface([], {
  "name": "string",
  "source": "string",
  "page": t.opt("number"),
  "reprintedAs": t.opt(t.array("ReprintedAs")),
  "category": t.opt("string"),
  "entries": t.array("Entry"),
  "prerequisite": t.opt(t.array("Prerequisite")),
  "hasFluffImages": t.opt("boolean"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Action,
  Feat,
};
export default exportedTypeSuite;
